# Configuration for Alacritty, the GPU enhanced terminal emulator.
[keyboard]
# bindings = [
#     { "key" = "Space", "mods" = "Control", "chars" = "\x00" }
# ]

[env]
# TERM: alacritty
# https://github.com/jwilm/alacritty/issues/2566
LC_CTYPE = "en_US.UTF-8"

[window]
decorations = "full"
startup_mode = "Windowed"

[scrolling]
history = 5000
# Scrolling distance multiplier.
multiplier = 3

## Cursor
[cursor]
style= {blinking = "Off", shape = "Block"}
unfocused_hollow = false

[general]
## Live config reload
live_config_reload = true
#background_opacity = 0.9

[font]
normal = {family = "Hack Nerd Font Mono", style = "Regular"}
bold = {family = "Hack Nerd Font Mono", style = "Bold"}
italic = {family = "Hack Nerd Font Mono", style = "Italic"}
bold_italic = {family = "Hack Nerd Font Mono", style = "Bold Italic"}
size = 14.0

[terminal]
# shell = { program = "wsl.exe ~ -d Ubuntu-22.04" }
